//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_Kamalov_wpf_320P.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academiki_Det
    {
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public System.DateTime Data_Rozhdeniya { get; set; }
        public string Specializatsiya { get; set; }
        public int God_Prisvoeniya_Zvaniya { get; set; }
    }
}
