//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_Kamalov_wpf_320P.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strani
    {
        public int ID { get; set; }
        public string Nazvanie { get; set; }
        public string Stolitsa { get; set; }
        public int Ploshad { get; set; }
        public int Naselenie { get; set; }
        public string Kontinent { get; set; }
    }
}
